"""Time-Series Momentum (TSMOM) strategy for a single asset (gold sleeve).

Strategy logic (Moskowitz, Ooi, Pedersen 2012 — "Time Series Momentum", JFE):

    Signal:  price > 200d SMA  AND  12-month return > 0  → long
             else                                         → flat (cash)

    Sizing:  vol-target: position weight = vol_target / realized_vol_66d
             capped at max_weight (1.0 = no leverage).

Pre-registration rationale (> 20 chars) is embedded in the ComposedConfig
generated by ``make_tsmom_config()``.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd

from trading_bot.features.price import realized_vol, tsmom_signal
from trading_bot.strategies.base import BaseStrategy, StrategyConfig


@dataclass(frozen=True)
class TSMOMConfig(StrategyConfig):
    symbol: str = "GLD"         # single asset ticker (GLD or IAU)
    sma_window: int = 200       # SMA period for trend filter
    mom_lookback: int = 252     # 12-month formation period
    vol_target: float = 0.10    # annualised vol target for position sizing
    vol_lookback: int = 66      # ~3 months for realised vol estimate
    max_weight: float = 1.0     # cap (no leverage above this)
    name: str = "tsmom_gold"


class TSMOMStrategy(BaseStrategy):
    """Single-asset TSMOM with vol-targeting.

    Works within the existing CrossSectionalBacktester:
    - ``rank()`` returns a Series with one element (the asset's signal: 0 or 1)
    - ``weights()`` returns a single-element Series with the vol-targeted weight
      (0.0 if signal is off, vol_target/rvol capped at max_weight if on)
    """

    def __init__(self, config: TSMOMConfig | None = None) -> None:
        self.cfg = config or TSMOMConfig()
        super().__init__(self.cfg)

    def rank(self, prices: pd.DataFrame, asof: pd.Timestamp) -> pd.Series:
        if self.cfg.symbol not in prices.columns:
            return pd.Series(dtype=float)
        sig = tsmom_signal(
            prices[[self.cfg.symbol]],
            asof,
            sma_window=self.cfg.sma_window,
            mom_lookback=self.cfg.mom_lookback,
        )
        return sig

    def weights(self, prices: pd.DataFrame, asof: pd.Timestamp) -> pd.Series:
        if self.cfg.symbol not in prices.columns:
            return pd.Series(dtype=float)

        sig = self.rank(prices, asof)
        if sig.empty or sig.iloc[0] == 0.0:
            return pd.Series(dtype=float)   # flat / all-cash

        # Vol-targeting: w = vol_target / σ_66d
        rvol = realized_vol(
            prices[[self.cfg.symbol]], asof, lookback=self.cfg.vol_lookback
        )
        if rvol.empty or rvol.iloc[0] <= 0 or np.isnan(rvol.iloc[0]):
            # Fallback to equal-weight 100% if vol is unavailable
            w = self.cfg.max_weight
        else:
            w = self.cfg.vol_target / float(rvol.iloc[0])
            w = min(w, self.cfg.max_weight)

        return pd.Series({self.cfg.symbol: w})
